[package]
name = "pixiv_rs"
version = "0.2.0"
edition = "2024"

[dependencies]
scraper = { version = "0.27.0", default-features = false }
ammonia = "4.1.4"
tokio = { version = "1", features = ["test-util", "full"] }
tokio-util = "0.7.18"
futures-util = "0.3.32"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "json", "stream", "http2", "form", "query", "socks", "system-proxy"] }
base64 = "0.22.1"
rand = "0.10"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11.0"
url = "2.5"
async-stream = "0.3.6"
futures-core = "0.3.32"
